### ISSUE TITLE
Modifications on arm and talos urdf/xacro files

### ISSUE THREAD

**Issue by marietonik** [AltziTS007/talos_sim#4]
For arm.urdf.xacro file:
* Changes and modifications in xml code.
* Removement of topics_nc parameter.

For talos.urdf.xacro file:
* Removement of topics_nc parameter.

Removing topics_nc parameter which is not supported in the files of realsense camera dependency. 
[Urdf_xacro_files.zip](https://github.com/user-attachments/files/15945320/Urdf_xacro_files.zip)

**Comment by AltziTS007** [comment]
which branch did you install and what is the error? Also keep in mind to update your repo from time to time.

**Comment by marietonik** [comment]
* Clone the Noetic-branch.
* Download dependencies according to readme file.
* Run the Catkin_make command.
* Run the roslaunch command according to readme file.

* Before making the changes in arm.urdf.xacro and  talos.urdf.xacro files the errors are the following.
* Tree of files also is the following txt.
[tree_src.txt](https://github.com/user-attachments/files/15945656/tree_src.txt)

![image_3](https://github.com/AltziTS007/talos_sim/assets/53263761/06a58224-5d8c-443b-8826-321bd8bc9e8d)
![image_1](https://github.com/AltziTS007/talos_sim/assets/53263761/7fb1aa2e-8bd9-4f26-82d3-8b4babe3a0f0)
![image_2](https://github.com/AltziTS007/talos_sim/assets/53263761/a7ff67ad-001e-40b5-a2b6-8dde374522a6)

**Comment by AltziTS007** [comment]
seems you are not using the recent version. Please clone the current branch.
